name: Generate metrics
on:
  schedule:
    - cron: "23 3 * * 1"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Generate metrics (simple clean)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: misato729
          filename: metrics.svg
          template: classic
          # ベース情報は最低限
          base: header, repositories, metadata
          config_timezone: Asia/Tokyo

          # 言語だけ（棒グラフ）
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 6

          # ノイズ源になりやすいものは切る
          plugin_achievements: no
          plugin_habits: no
          plugin_calendar: no
          plugin_isocalendar: no

      - name: Commit metrics.svg
        uses: EndBug/add-and-commit@v9
        with:
          add: metrics.svg
          message: "chore: update metrics (simple clean)"
