name: Generate metrics

on:
  schedule:
    - cron: "23 3 * * 1"   # 毎週月曜 12:23 JST 頃（UTC換算）
  workflow_dispatch:        # 手動実行も可能

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: misato729
          filename: metrics.svg
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Tokyo
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_notable: yes

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          add: "metrics.svg"
          message: "chore: update metrics"
